AWSTemplateFormatVersion: '2010-09-09'
Description: '[E1] VPC Infrastructure with Mandatory Tags'

Parameters:
  ProjectName: { Type: String }
  EnvironmentName: { Type: String }
  VpcCidr: { Type: String }

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc
        - Key: Entorno # Tag requerido por SCP
          Value: desarrollo

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-east-1a
      CidrBlock: !Select [ 0, !Cidr [ !Ref VpcCidr, 1, 8 ] ]
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-pub-sub
        - Key: Entorno # Tag requerido por SCP
          Value: desarrollo