AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Infrastructure with Mandatory Governance Tags'

Parameters:
  ProjectName:
    Type: String
    Default: ia-app
  EnvironmentName:
    Type: String
    Default: development
  VpcCidr:
    Type: String
    Default: 10.10.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc
        # Este tag satisface la política SCP a nivel de recurso (ec2:CreateVpc)
        - Key: Entorno
          Value: desarrollo
        - Key: Project
          Value: !Ref ProjectName