name: "[E1/E3] AWS Infrastructure Deployment"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write   # Obligatorio para OIDC
  contents: read    # Obligatorio para leer el repo

jobs:
  deploy-dev:
    name: "Deploy to Development"
    runs-on: ubuntu-latest
    # Se ejecuta solo si es la rama main o develop
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_DEV }} # El ARN que pusiste en Variables
          aws-region: us-east-1
          role-session-name: gha-session-${{ github.run_id }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity # Esto valida la cuenta 245650696072

      - name: Deploy VPC Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: sow-001-vpc-dev
          template: SOW/infrastructure/cloudformation/dev/01-vpc.yaml
          parameter-overrides: >-
            ProjectName=ia-app,
            EnvironmentName=development,
            VpcCidr=10.10.0.0/16,
            AvailabilityZone=us-east-1a
          no-fail-on-empty-changeset: "1"