AWSTemplateFormatVersion: '2010-09-09'
Description: 'QA VPC Infrastructure - Multi-Account Strategy'

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  VpcCidr:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-vpc
        # Tag de cumplimiento para la SCP multi-cuenta
        - Key: Entorno
          Value: qa
        - Key: Project
          Value: !Ref ProjectName

  # Subnet Pública de QA
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [ 0, !Cidr [ !Ref VpcCidr, 1, 8 ] ] # 10.20.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-public-sn
        - Key: Entorno
          Value: qa

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-VpcId